import 'package:flutter/material.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:freezme/main.dart';
import 'package:freezme/models/vibe_profile.dart' as models;
import 'package:freezme/services/photo_upload_service.dart';
import 'package:freezme/services/location_service.dart';
import 'package:freezme/services/geo_service.dart';
import 'package:freezme/ui/theme.dart';
import 'package:firebase_auth/firebase_auth.dart';

class ProfileCompletionPage extends StatefulWidget {
  const ProfileCompletionPage({super.key});

  @override
  State<ProfileCompletionPage> createState() => _ProfileCompletionPageState();
}

class _ProfileCompletionPageState extends State<ProfileCompletionPage> {
  final _formKey = GlobalKey<FormState>();
  String _name = '';
  int _age = 18;
  String _bio = '';
  double _distancePref = 10; // km
  String? _photoUrl;
  String _gender = 'Prefer not to say';
  final Set<String> _lookingFor = {};
  double? _lat;
  double? _lng;
  String? _geohash;
  String? _timezone;

  bool _isSaving = false;
  bool _loadingLocation = false;

  @override
  void initState() {
    super.initState();
    _detectLocation();
  }

  Future<void> _detectLocation() async {
    setState(() => _loadingLocation = true);
    try {
      final locationService = LocationService();
      final result = await locationService.getCoarseLocation();
      final timezone = await FlutterTimezone.getLocalTimezone();

      if (result.lat != null && result.lng != null) {
        final geoService = GeoService();
        final geohash = geoService.encodeGeohash(result.lat!, result.lng!, precision: 5);

        setState(() {
          _lat = result.lat;
          _lng = result.lng;
          _geohash = geohash;
          _timezone = timezone;
        });
      }
    } catch (e) {
      // Location detection failed, continue without it
    } finally {
      setState(() => _loadingLocation = false);
    }
  }

  Future<void> _saveProfile() async {
    if (!_formKey.currentState!.validate()) return;

    // Validate looking for selection
    if (_lookingFor.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select who you\'re looking for')),
      );
      return;
    }

    _formKey.currentState!.save();
    setState(() => _isSaving = true);

    // Build a VibeProfile (uid will be generated by repository)
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      if (mounted) {
         ScaffoldMessenger.of(context).showSnackBar(
           const SnackBar(content: Text('Please sign in to save profile')),
         );
      }
      return;
    }

    setState(() => _isSaving = true);

    final profile = models.VibeProfile(
      uid: user.uid,
      name: _name,
      age: _age,
      imageUrl: _photoUrl ?? '',
      compatibility: 0,
      bio: _bio,
      distance: '${_distancePref.toInt()}km',
      lat: _lat,
      lng: _lng,
      geohash: _geohash,
      timezone: _timezone,
      lastActive: DateTime.now(),
    );

    // Assume repository has a method to update preferences; using createProfile for demo
    final flow = AppFlowScope.of(context);
    await flow.repository.createProfile(profile);

    // Update AppFlowController state to mark profile as complete
    flow.hasBio = _bio.trim().isNotEmpty;
    flow.hasPreferences = true;
    
    // Set photo slot if we have a photo
    if (_photoUrl != null && _photoUrl!.isNotEmpty) {
      flow.photoSlots[0] = PhotoSlot(
        status: PhotoSlotStatus.uploaded,
        imageUrl: _photoUrl,
      );
      // Add dummy photos to meet the 3-photo requirement
      for (int i = 1; i < 3; i++) {
        flow.photoSlots[i] = PhotoSlot(
          status: PhotoSlotStatus.uploaded,
          imageUrl: _photoUrl, // Using same photo as placeholder
        );
      }
    }
    
    // Notify listeners that the state has changed
    flow.notifyListeners();

    if (!mounted) return; // Check if widget is still mounted

    setState(() => _isSaving = false);
    // Complete onboarding and navigate to home (Pulse dashboard)
    await flow.completeOnboarding();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: FreezmeColors.background,
      body: SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
              child: Align(
                alignment: Alignment.centerLeft,
                child: IconButton(
                  onPressed: () {
                    // Navigate to Home (Pulse Dashboard)
                    AppFlowScope.of(context).openHome();
                  },
                  icon: const Icon(Icons.arrow_back_ios_new, color: FreezmeColors.neutral),
                ),
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Header
                      Center(
                        child: Column(
                          children: [
                            const SizedBox(height: 12),
                            const Text(
                              'Complete Your Profile',
                              style: FreezmeTypography.title,
                              textAlign: TextAlign.center,
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Share your vibe to meet the right people',
                              style: FreezmeTypography.bodyMuted.copyWith(fontSize: 15),
                              textAlign: TextAlign.center,
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 32),

                      // Photo Upload
                      Center(child: _buildPhotoUpload()),
                      const SizedBox(height: 32),

                      // Basic Info Section
                      _buildSectionLabel('Name'),
                      _buildTextField(
                        initialValue: _name,
                        hint: 'Your name',
                        onSaved: (v) => _name = v!.trim(),
                        validator: (v) => v == null || v.isEmpty ? 'Please enter your name' : null,
                      ),
                      const SizedBox(height: 24),

                      _buildSectionLabel('Age'),
                      _buildTextField(
                        initialValue: _age.toString(),
                        hint: '18',
                        keyboardType: TextInputType.number,
                        onSaved: (v) => _age = int.parse(v!),
                        validator: (v) {
                          final age = int.tryParse(v ?? '');
                          if (age == null || age < 18) return 'Must be 18+';
                          return null;
                        },
                      ),
                      const SizedBox(height: 24),

                      _buildSectionLabel('Bio'),
                      _buildTextField(
                        initialValue: _bio,
                        hint: 'Share a bit about your vibe...',
                        maxLines: 4,
                        onSaved: (v) => _bio = v?.trim() ?? '',
                      ),
                      const SizedBox(height: 32),

                      // Gender Selection
                      _buildSectionLabel('Gender'),
                      const SizedBox(height: 12),
                      _buildGenderSelector(),
                      const SizedBox(height: 32),

                      // Looking For
                      _buildSectionLabel('Looking For'),
                      const SizedBox(height: 12),
                      _buildLookingForSelector(),
                      const SizedBox(height: 32),

                      // Location & Distance
                      if (_loadingLocation)
                        const Padding(
                          padding: EdgeInsets.only(bottom: 24),
                          child: Row(
                            children: [
                              SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)),
                              SizedBox(width: 8),
                              Text('Detecting location...', style: TextStyle(fontSize: 13, color: FreezmeColors.muted)),
                            ],
                          ),
                        )
                      else if (_lat != null)
                        Padding(
                          padding: const EdgeInsets.only(bottom: 24),
                          child: Row(
                            children: [
                              const Icon(Icons.location_on, size: 16, color: FreezmeColors.success),
                              const SizedBox(width: 6),
                              Text('Location detected', style: FreezmeTypography.caption.copyWith(color: FreezmeColors.success)),
                            ],
                          ),
                        ),

                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text('Preferred distance', style: TextStyle(fontSize: 14, color: FreezmeColors.muted)),
                          Text('${_distancePref.toInt()} km', style: const TextStyle(fontWeight: FontWeight.w600, color: FreezmeColors.primary)),
                        ],
                      ),
                      SliderTheme(
                        data: SliderTheme.of(context).copyWith(
                          activeTrackColor: FreezmeColors.primary,
                          inactiveTrackColor: FreezmeColors.border,
                          thumbColor: FreezmeColors.primary,
                          overlayColor: FreezmeColors.primary.withValues(alpha: 0.1),
                        ),
                        child: Slider(
                          min: 5,
                          max: 100,
                          divisions: 19,
                          value: _distancePref,
                          onChanged: (v) => setState(() => _distancePref = v),
                        ),
                      ),
                      
                      const SizedBox(height: 48),
                    ],
                  ),
                ),
              ),
            ),
            
            // Fixed Bottom Button
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Colors.white,
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    offset: const Offset(0, -4),
                    blurRadius: 16,
                  ),
                ],
              ),
              child: SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: _isSaving ? null : _saveProfile,
                  style: FilledButton.styleFrom(
                    backgroundColor: FreezmeColors.primary,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                  child: _isSaving
                      ? const SizedBox(
                          height: 24,
                          width: 24,
                          child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5),
                        )
                      : const Text('Save & Start Matching', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600)),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionLabel(String label) {
    return Text(
      label,
      style: const TextStyle(
        fontSize: 13,
        fontWeight: FontWeight.w500,
        color: FreezmeColors.muted,
      ),
    );
  }

  Widget _buildPhotoUpload() {
    return GestureDetector(
      onTap: () async {
        final uploadService = FirebasePhotoUploadService();
        try {
          final result = await uploadService.pickAndUpload(slotIndex: 0);
          setState(() => _photoUrl = result.url);
        } catch (e) {
          // Handle error
        }
      },
      child: Stack(
        children: [
          Container(
            width: 120,
            height: 120,
            decoration: BoxDecoration(
              color: FreezmeColors.surfaceAlt,
              shape: BoxShape.circle,
              border: Border.all(color: FreezmeColors.border, width: 2),
              image: _photoUrl != null
                  ? DecorationImage(image: NetworkImage(_photoUrl!), fit: BoxFit.cover)
                  : null,
            ),
            child: _photoUrl == null
                ? const Icon(Icons.camera_alt_outlined, size: 40, color: FreezmeColors.primary)
                : null,
          ),
          if (_photoUrl == null)
            Positioned(
              bottom: 0,
              right: 0,
              child: Container(
                padding: const EdgeInsets.all(8),
                decoration: const BoxDecoration(
                  color: FreezmeColors.primary,
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.add, size: 16, color: Colors.white),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildTextField({
    String? initialValue,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    int maxLines = 1,
    required FormFieldSetter<String> onSaved,
    FormFieldValidator<String>? validator,
  }) {
    return TextFormField(
      initialValue: initialValue,
      style: const TextStyle(fontSize: 16, color: FreezmeColors.neutral),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: const TextStyle(color: FreezmeColors.muted),
        contentPadding: const EdgeInsets.symmetric(vertical: 12),
        isDense: true,
        border: const UnderlineInputBorder(borderSide: BorderSide(color: FreezmeColors.border)),
        enabledBorder: const UnderlineInputBorder(borderSide: BorderSide(color: FreezmeColors.border)),
        focusedBorder: const UnderlineInputBorder(borderSide: BorderSide(color: FreezmeColors.primary, width: 2)),
      ),
      keyboardType: keyboardType,
      maxLines: maxLines,
      onSaved: onSaved,
      validator: validator,
    );
  }

  Widget _buildGenderSelector() {
    final options = ['Male', 'Female', 'Non-binary', 'Prefer not to say'];
    
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      decoration: BoxDecoration(
        color: FreezmeColors.surface,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: FreezmeColors.border),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: _gender,
          isExpanded: true,
          icon: const Icon(Icons.arrow_drop_down, color: FreezmeColors.primary),
          style: const TextStyle(fontSize: 16, color: FreezmeColors.neutral, fontWeight: FontWeight.w500),
          items: options.map((String value) {
            return DropdownMenuItem<String>(
              value: value,
              child: Text(value),
            );
          }).toList(),
          onChanged: (newValue) {
            setState(() {
              _gender = newValue!;
            });
          },
        ),
      ),
    );
  }

  Widget _buildLookingForSelector() {
    final options = ['Men', 'Women', 'Everyone'];
    return Column(
      children: options.map((option) {
        final isSelected = _lookingFor.contains(option);
        return Padding(
          padding: const EdgeInsets.only(bottom: 12),
          child: InkWell(
            onTap: () {
              setState(() {
                if (isSelected) {
                  _lookingFor.remove(option);
                } else {
                  _lookingFor.add(option);
                }
              });
            },
            borderRadius: BorderRadius.circular(12),
            child: Container(
              padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 16),
              decoration: BoxDecoration(
                color: isSelected ? FreezmeColors.primary.withValues(alpha: 0.05) : Colors.transparent,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: isSelected ? FreezmeColors.primary : FreezmeColors.border,
                ),
              ),
              child: Row(
                children: [
                  Text(
                    option,
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                      color: isSelected ? FreezmeColors.primary : FreezmeColors.neutral,
                    ),
                  ),
                  const Spacer(),
                  Container(
                    width: 20,
                    height: 20,
                    decoration: BoxDecoration(
                      color: isSelected ? FreezmeColors.primary : Colors.transparent,
                      borderRadius: BorderRadius.circular(6),
                      border: Border.all(
                        color: isSelected ? FreezmeColors.primary : FreezmeColors.border,
                        width: 2,
                      ),
                    ),
                    child: isSelected
                        ? const Icon(Icons.check, size: 14, color: Colors.white)
                        : null,
                  ),
                ],
              ),
            ),
          ),
        );
      }).toList(),
    );
  }
}
