import 'package:flutter/material.dart';
import 'package:freezme/main.dart';
import 'package:freezme/models/vibe_profile.dart';
import 'package:freezme/services/photo_upload_service.dart';
import 'package:freezme/data/freezme_repository.dart';

class ProfileCompletionPage extends StatefulWidget {
  const ProfileCompletionPage({Key? key}) : super(key: key);

  @override
  State<ProfileCompletionPage> createState() => _ProfileCompletionPageState();
}

class _ProfileCompletionPageState extends State<ProfileCompletionPage> {
  final _formKey = GlobalKey<FormState>();
  String _name = '';
  int _age = 18;
  String _bio = '';
  double _distancePref = 10; // km
  String? _photoUrl;

  bool _isSaving = false;

  Future<void> _saveProfile() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();
    setState(() => _isSaving = true);
    // Build a VibeProfile (uid will be generated by repository)
    final profile = VibeProfile(
      id: 0,
      name: _name,
      age: _age,
      imageUrl: _photoUrl ?? '',
      compatibility: 0,
      bio: _bio,
      distance: '${_distancePref.toInt()}km',
    );
    // Assume repository has a method to update preferences; using createProfile for demo
    final repo = FreezmeRepository.instance; // placeholder static accessor
    await repo.createProfile(profile);
    setState(() => _isSaving = false);
    // Complete onboarding and navigate to home (Pulse dashboard)
    await AppFlowScope.of(context).completeOnboarding();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Complete Your Profile')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              // Photo upload placeholder
              Center(
                child: GestureDetector(
                  onTap: () async {
                    // Use existing PhotoUploadService (implementation omitted)
                    final url = await PhotoUploadService().pickAndUpload();
                    setState(() => _photoUrl = url);
                  },
                  child: CircleAvatar(
                    radius: 48,
                    backgroundImage: _photoUrl != null ? NetworkImage(_photoUrl!) : null,
                    child: _photoUrl == null ? const Icon(Icons.camera_alt, size: 32) : null,
                  ),
                ),
              ),
              const SizedBox(height: 24),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Name'),
                validator: (v) => v == null || v.isEmpty ? 'Enter a name' : null,
                onSaved: (v) => _name = v!.trim(),
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Age'),
                keyboardType: TextInputType.number,
                initialValue: '18',
                validator: (v) {
                  final age = int.tryParse(v ?? '');
                  if (age == null || age < 18) return 'Must be 18+';
                  return null;
                },
                onSaved: (v) => _age = int.parse(v!),
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Bio'),
                maxLines: 3,
                onSaved: (v) => _bio = v?.trim() ?? '',
              ),
              const SizedBox(height: 12),
              Text('Preferred distance (${_distancePref.toInt()} km)'),
              Slider(
                min: 1,
                max: 50,
                divisions: 49,
                value: _distancePref,
                label: '${_distancePref.toInt()} km',
                onChanged: (v) => setState(() => _distancePref = v),
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _isSaving ? null : _saveProfile,
                child: _isSaving
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text('Save & Continue'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
