import 'package:flutter/material.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:freezme/main.dart';
import 'package:freezme/models/vibe_profile.dart' as models;
import 'package:freezme/services/photo_upload_service.dart';
import 'package:freezme/services/location_service.dart';
import 'package:freezme/services/geo_service.dart';

class ProfileCompletionPage extends StatefulWidget {
  const ProfileCompletionPage({super.key});

  @override
  State<ProfileCompletionPage> createState() => _ProfileCompletionPageState();
}

class _ProfileCompletionPageState extends State<ProfileCompletionPage> {
  final _formKey = GlobalKey<FormState>();
  String _name = '';
  int _age = 18;
  String _bio = '';
  double _distancePref = 10; // km
  String? _photoUrl;
  String _gender = 'Prefer not to say';
  final Set<String> _lookingFor = {};
  double? _lat;
  double? _lng;
  String? _geohash;
  String? _timezone;

  bool _isSaving = false;
  bool _loadingLocation = false;

  @override
  void initState() {
    super.initState();
    _detectLocation();
  }

  Future<void> _detectLocation() async {
    setState(() => _loadingLocation = true);
    try {
      final locationService = LocationService();
      final result = await locationService.getCoarseLocation();
      final timezone = await FlutterTimezone.getLocalTimezone();

      if (result.lat != null && result.lng != null) {
        final geoService = GeoService();
        final geohash = geoService.encodeGeohash(result.lat!, result.lng!, precision: 5);

        setState(() {
          _lat = result.lat;
          _lng = result.lng;
          _geohash = geohash;
          _timezone = timezone;
        });
      }
    } catch (e) {
      // Location detection failed, continue without it
    } finally {
      setState(() => _loadingLocation = false);
    }
  }

  Future<void> _saveProfile() async {
    if (!_formKey.currentState!.validate()) return;

    // Validate looking for selection
    if (_lookingFor.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select who you\'re looking for')),
      );
      return;
    }

    _formKey.currentState!.save();
    setState(() => _isSaving = true);

    // Build a VibeProfile (uid will be generated by repository)
    final profile = models.VibeProfile(
      uid: '', // Will be set by repository
      id: 0,
      name: _name,
      age: _age,
      imageUrl: _photoUrl ?? '',
      compatibility: 0,
      bio: _bio,
      distance: '${_distancePref.toInt()}km',
      lat: _lat,
      lng: _lng,
      geohash: _geohash,
      timezone: _timezone,
      lastActive: DateTime.now(),
    );

    // Assume repository has a method to update preferences; using createProfile for demo
    final repo = AppFlowScope.of(context).repository;
    await repo.createProfile(profile);

    if (!mounted) return; // Check if widget is still mounted

    setState(() => _isSaving = false);
    // Complete onboarding and navigate to home (Pulse dashboard)
    await AppFlowScope.of(context).completeOnboarding();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Complete Your Profile')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              // Photo upload placeholder
              Center(
                child: GestureDetector(
                  onTap: () async {
                    // Use existing PhotoUploadService (implementation omitted)
                    final uploadService = FirebasePhotoUploadService();
                    final result = await uploadService.pickAndUpload(slotIndex: 0);
                    setState(() => _photoUrl = result.url);
                  },
                  child: CircleAvatar(
                    radius: 48,
                    backgroundImage: _photoUrl != null ? NetworkImage(_photoUrl!) : null,
                    child: _photoUrl == null ? const Icon(Icons.camera_alt, size: 32) : null,
                  ),
                ),
              ),
              const SizedBox(height: 24),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Name'),
                validator: (v) => v == null || v.isEmpty ? 'Enter a name' : null,
                onSaved: (v) => _name = v!.trim(),
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Age'),
                keyboardType: TextInputType.number,
                initialValue: '18',
                validator: (v) {
                  final age = int.tryParse(v ?? '');
                  if (age == null || age < 18) return 'Must be 18+';
                  return null;
                },
                onSaved: (v) => _age = int.parse(v!),
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Bio'),
                maxLines: 3,
                onSaved: (v) => _bio = v?.trim() ?? '',
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                decoration: const InputDecoration(labelText: 'Gender'),
                value: _gender,
                items: const [
                  DropdownMenuItem(value: 'Male', child: Text('Male')),
                  DropdownMenuItem(value: 'Female', child: Text('Female')),
                  DropdownMenuItem(value: 'Non-binary', child: Text('Non-binary')),
                  DropdownMenuItem(value: 'Prefer not to say', child: Text('Prefer not to say')),
                ],
                onChanged: (v) => setState(() => _gender = v!),
              ),
              const SizedBox(height: 16),
              const Text('Looking For', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500)),
              const SizedBox(height: 8),
              CheckboxListTile(
                title: const Text('Men'),
                value: _lookingFor.contains('Men'),
                onChanged: (checked) {
                  setState(() {
                    if (checked == true) {
                      _lookingFor.add('Men');
                    } else {
                      _lookingFor.remove('Men');
                    }
                  });
                },
              ),
              CheckboxListTile(
                title: const Text('Women'),
                value: _lookingFor.contains('Women'),
                onChanged: (checked) {
                  setState(() {
                    if (checked == true) {
                      _lookingFor.add('Women');
                    } else {
                      _lookingFor.remove('Women');
                    }
                  });
                },
              ),
              CheckboxListTile(
                title: const Text('Everyone'),
                value: _lookingFor.contains('Everyone'),
                onChanged: (checked) {
                  setState(() {
                    if (checked == true) {
                      _lookingFor.add('Everyone');
                    } else {
                      _lookingFor.remove('Everyone');
                    }
                  });
                },
              ),
              const SizedBox(height: 8),
              if (_loadingLocation)
                const Row(
                  children: [
                    SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)),
                    SizedBox(width: 8),
                    Text('Detecting location...', style: TextStyle(fontSize: 12)),
                  ],
                )
              else if (_lat != null && _lng != null)
                const Row(
                  children: [
                    Icon(Icons.location_on, size: 16, color: Colors.green),
                    SizedBox(width: 4),
                    Text('Location detected', style: TextStyle(fontSize: 12, color: Colors.green)),
                  ],
                ),
              const SizedBox(height: 12),
              Text('Preferred distance (${_distancePref.toInt()} km)'),
              Slider(
                min: 1,
                max: 50,
                divisions: 49,
                value: _distancePref,
                label: '${_distancePref.toInt()} km',
                onChanged: (v) => setState(() => _distancePref = v),
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _isSaving ? null : _saveProfile,
                child: _isSaving
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text('Save & Continue'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
