include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/data/firestore_freezme_repository.dart
    - lib/data/cloud_functions_freezme_repository.dart
    - integration_test/**
  errors:
    unused_local_variable: error
    unused_field: error
    unused_element: error
    dead_code: error
    avoid_print: warning
    deprecated_member_use: error
    unreachable_switch_default: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
